export const secondWordBase = [
  { targetWord: 'squad', translating: 'бригада' },
  { targetWord: 'flimsy', translating: 'неосновательный' },
  { targetWord: 'thorough', translating: 'подробный' },
  { targetWord: 'flawed', translating: 'некорректный' },
  { targetWord: 'boldly', translating: 'дерзко' },
  { targetWord: 'shorthand', translating: 'условное обозначение' },
  { targetWord: 'missile', translating: 'реактивный снаряд' },
  { targetWord: 'missile', translating: 'ракета' },
  { targetWord: 'oath', translating: 'клятва' },
  { targetWord: 'devoted', translating: 'преданный' },
  { targetWord: 'intrusive.', translating: 'навязчивый' },
  { targetWord: 'growling', translating: 'рычать' },
  { targetWord: 'Wreak', translating: 'наносить' },
  { targetWord: 'Wreak', translating: 'обрушить' },
  { targetWord: 'relic', translating: 'пережиток' },
  { targetWord: 'depreciate', translating: 'умалять' },
  { targetWord: 'likelihood', translating: 'вероятностный' },
  { targetWord: 'invoked', translating: 'вызванный' },
  { targetWord: 'pending', translating: 'в ожидании' },
  { targetWord: 'speed bump', translating: 'лежачий полицейский' },
  { targetWord: 'instant', translating: 'момент' },
  { targetWord: 'fateful', translating: 'роковой' },
  { targetWord: 'fateful', translating: 'решающий' },
  { targetWord: 'accident', translating: 'несчастный случай' },
  { targetWord: 'hubby', translating: 'муженек' },
  { targetWord: 'flatter', translating: 'льстить' },
  { targetWord: 'end up', translating: 'оказываться' },
  { targetWord: 'incident', translating: 'происшествие' },
  { targetWord: 'episode', translating: 'событие' },
  { targetWord: 'breakthrough', translating: 'прорыв' },
  { targetWord: 'eternity', translating: 'бесконечность' },
  { targetWord: 'irrespective', translating: 'независимо' },
  { targetWord: 'obsessed', translating: 'одержимый' },
  { targetWord: 'incompatible', translating: 'несовместимый' },
  { targetWord: 'keen', translating: 'проницательный' },
  { targetWord: 'immune', translating: 'невосприимчивый' },
  { targetWord: 'general practitioner', translating: 'врач-терапевт' },
  { targetWord: 'word for word', translating: 'дословно' },
  { targetWord: 'sign language', translating: 'жестовый язык' },
  { targetWord: 'pull off', translating: 'добиваться' },
  { targetWord: 'dummy', translating: 'подставной' },
  { targetWord: 'quirky', translating: 'причудливый' },
  { targetWord: 'cluster', translating: 'скопление ' },
  { targetWord: 'path', translating: 'контур' },
  { targetWord: 'delimiter', translating: 'разделитель данных' },
  { targetWord: 'trapped', translating: 'загнанный в угол' },
  { targetWord: 'spread', translating: 'распространять, распространяться' },
  { targetWord: 'represent', translating: 'означать' },
  { targetWord: 'sabotage', translating: 'саботировать' },
  { targetWord: 'slander', translating: 'марать' },
  { targetWord: 'sensitive', translating: 'уязвимый' },
  { targetWord: 'campaign', translating: 'проводить кампанию' },
  { targetWord: 'leak', translating: 'утечка' },
  { targetWord: 'leak', translating: 'сливать информацию' },
  { targetWord: 'insulting', translating: 'оскорбительный' },
  { targetWord: 'clogged', translating: 'засорённый' },
  { targetWord: 'shame', translating: 'стыдить' },
  { targetWord: 'refugee camp', translating: 'лагерь беженцев' },
  { targetWord: 'fresh water', translating: 'пресная вода' },
  { targetWord: 'overthink', translating: 'зацикливаться' },
  { targetWord: 'offer', translating: 'предлагать' },
  { targetWord: 'consider', translating: 'учитывать' },
  { targetWord: 'consider', translating: 'рассматривать' },
  { targetWord: 'coincide', translating: 'совпадать' },
  { targetWord: 'stunned', translating: 'потрясенный' },
  { targetWord: 'bucket list', translating: 'список желаний' },
  { targetWord: 'burst', translating: 'вспышка' },
  { targetWord: 'lunacy', translating: 'безумие' },
  {
    targetWord: 'bipolar disorder',
    translating: 'биполярное аффективное расстройство'
  },
  { targetWord: 'predator', translating: 'хищник' },
  { targetWord: 'thrill', translating: 'возбуждение' },
  { targetWord: 'endurance', translating: 'выносливость' },
  { targetWord: 'unaware', translating: 'не знающий' },
  { targetWord: 'bravery', translating: 'храбрость' },
  { targetWord: 'life-threatening', translating: 'смертельно опасный' },
  { targetWord: 'struggle with', translating: 'бороться с' },
  { targetWord: 'extend', translating: 'расширять' },
  { targetWord: 'wear out', translating: 'изматывать' },
  { targetWord: 'hectic', translating: 'суматошный; лихорадочный' },
  { targetWord: 'enthuse', translating: 'вызывать энтузиазм' },
  { targetWord: 'savour', translating: 'насладиться' },
  { targetWord: 'accomplishment', translating: 'достижение ' },
  { targetWord: 'preconceived', translating: 'предвзятый' },
  { targetWord: 'hustle and bustle', translating: 'шум и суета' },
  { targetWord: 'notion', translating: 'представление' },
  { targetWord: 'grounded', translating: 'приземлённый' },
  { targetWord: 'enhance', translating: 'увеличивать' },
  { targetWord: 'downside', translating: 'отрицательная сторона, недостаток' },
  { targetWord: 'pioneer', translating: 'открывать' },
  { targetWord: 'split', translating: 'разделять, распределять' },
  { targetWord: 'dominant', translating: 'главный, господствующий' },
  { targetWord: 'needless', translating: 'излишний' },
  { targetWord: 'handle', translating: 'справляться' },
  { targetWord: 'stifle', translating: 'утаивать' },
  { targetWord: 'well-off', translating: 'состоятельный' },
  { targetWord: 'well-off', translating: 'зажиточный' },
  { targetWord: 'spill the beans', translating: 'проболтаться' },
  { targetWord: 'embassy', translating: 'посольство' },
  { targetWord: 'vigorous', translating: 'энергичный' },
  { targetWord: 'nonetheless', translating: 'однако' },
  { targetWord: 'perishable', translating: 'скоропортящийся' },
  { targetWord: 'heartbroken', translating: 'убитый горем' },
  { targetWord: 'adrenaline', translating: 'адреналин' },
  { targetWord: 'betrayal', translating: 'предательство' },
  { targetWord: 'traitor', translating: 'изменник ' },
  { targetWord: 'euphoric', translating: 'эйфорический' },
  { targetWord: 'vision', translating: 'видение' },
  { targetWord: 'reflect on⁄upon', translating: 'размышлять над' },
  { targetWord: 'blur the line', translating: 'стирать границу(ы)' },
  { targetWord: 'involuntary', translating: 'невольный' },
  { targetWord: 'skim', translating: 'быстрое чтение' },
  { targetWord: 'lucid', translating: 'ясный' },
  { targetWord: 'volitional', translating: 'волевой' },
  { targetWord: 'headfirst', translating: 'головой вперёд' },
  { targetWord: 'far-fetched', translating: 'притянутый за уши' },
  { targetWord: 'with ease', translating: 'с лёгкостью' },
  { targetWord: 'lingering', translating: 'затяжной' },
  { targetWord: 'open up', translating: 'раскрываться' },
  { targetWord: 'stuck', translating: 'застрявший' },
  { targetWord: 'plight', translating: 'затруднительное положение' },
  { targetWord: 'bottle up', translating: 'сдерживать' },
  { targetWord: 'stigmatise', translating: 'клеймить' },
  { targetWord: 'well-being', translating: 'благополучие' },
  { targetWord: 'compassion', translating: 'сострадание' },
  { targetWord: 'introspection', translating: 'самоанализ' },
  { targetWord: 'relief', translating: 'облегчение' },
  { targetWord: 'first aid', translating: 'первая помощь' },
  { targetWord: 'stigma', translating: 'клеймо позора' },
  { targetWord: 'distress', translating: 'страдание' },
  { targetWord: 'captivating', translating: 'очаровательный' },
  { targetWord: 'speculate', translating: 'предполагать' },
  { targetWord: 'undoubtedly', translating: 'несомненно' },
  { targetWord: 'bolt', translating: 'глотать' },
  { targetWord: 'boil down', translating: 'вываривать' },
  { targetWord: 'cut up', translating: 'нарезать' },
  { targetWord: 'prop', translating: 'декорация' },
  { targetWord: 'intangible', translating: 'неуловимый' },
  { targetWord: 'bias', translating: 'предрассудок' },
  { targetWord: 'impetus', translating: 'толчок' },
  { targetWord: 'foster', translating: 'способствовать развитию' },
  { targetWord: 'seek', translating: 'искать' },
  { targetWord: 'allot', translating: 'отводить' },
  { targetWord: 'cultivate', translating: 'развивать' },
  { targetWord: 'high-profile', translating: 'привлекающий внимание' },
  { targetWord: 'current affairs', translating: 'текущие события' },
  { targetWord: 'resolve', translating: 'решать' },
  { targetWord: 'apron', translating: 'фартук' },
  { targetWord: 'phobia', translating: 'фобия' },
  { targetWord: 'frequent', translating: 'часто посещать' },
  { targetWord: 'conquer', translating: 'завоёвывать' },
  { targetWord: 'bring out', translating: 'выявлять' },
  { targetWord: 'bring out', translating: 'выпускать' },
  { targetWord: 'fundraise', translating: 'собирать деньги' },
  { targetWord: 'lucid', translating: 'вразумительный' },
  { targetWord: 'go to pieces', translating: 'терять присутствие духа' },
  { targetWord: 'poultry', translating: 'домашняя птица' },
  { targetWord: 'greedy', translating: 'жадный' },
  { targetWord: 'pastry', translating: 'тесто' },
  { targetWord: 'substitute', translating: 'заменять' },
  { targetWord: 'refreshment', translating: 'закуска' },
  { targetWord: 'pig out', translating: 'объедаться' },
  { targetWord: 'swallow', translating: 'глотать' },
  { targetWord: 'superb', translating: 'великолепный' },
  { targetWord: 'superb', translating: 'великолепный' },
  { targetWord: 'staple', translating: 'основной' },
  { targetWord: 'starve', translating: 'умирать от голода' },
  { targetWord: 'no-go', translating: 'нерабочий' },
  { targetWord: 'life vest', translating: 'спасательный жилет' },
  { targetWord: 'rank', translating: 'занимать место' },
  { targetWord: 'back away', translating: 'отступать' },
  { targetWord: 'out of the question', translating: 'совершенно исключено' },
  { targetWord: 'dead drop', translating: 'тайник' },
  { targetWord: 'spouse', translating: 'супруг; супруга' },
  { targetWord: 'touch base', translating: 'пообщаться' },
  { targetWord: 'esports', translating: 'киберспорт' },
  { targetWord: 'handyman', translating: 'мастер на все руки' },
  { targetWord: 'application', translating: 'приложение' },
  { targetWord: 'notwithstanding', translating: 'вопреки' },
  { targetWord: 'rife', translating: 'распространённый' },
  { targetWord: 'evolve', translating: 'развиваться' },
  { targetWord: 'fade', translating: 'исчезновение' },
  { targetWord: 'fade', translating: 'блёкнуть' },
  { targetWord: 'fade', translating: 'постепенно исчезать' },
  { targetWord: 'character', translating: 'символ' },
  { targetWord: 'come in handy', translating: 'пригодиться' },
  { targetWord: 'daydream', translating: 'мечтать' },
  { targetWord: 'quarrel', translating: 'ссора' },
  { targetWord: 'defensive', translating: 'защитный' },
  { targetWord: 'beat around the bush', translating: 'ходить вокруг да около' },
  { targetWord: 'incessantly', translating: 'постоянно' },
  { targetWord: 'put differently', translating: 'другими словами' },
  { targetWord: 'subtle', translating: 'неуловимый' },
  { targetWord: 'belittle', translating: 'принижать' },
  { targetWord: 'contemplate', translating: 'рассматривать' },
  { targetWord: 'evil spirit', translating: 'злой дух' },
  { targetWord: 'scatter', translating: 'рассеивать' },
  { targetWord: 'exclude', translating: 'исключать' },
  { targetWord: 'inexplicable', translating: 'необъяснимый' },
  { targetWord: 'antsy', translating: 'беспокойный' },
  { targetWord: 'establish', translating: 'устанавливать' },
  { targetWord: 'layout', translating: 'план' },
  { targetWord: 'layout', translating: 'компоновка' },
  { targetWord: 'enable', translating: 'давать возможность' },
  { targetWord: 'expand', translating: 'расширять' },
  { targetWord: 'circle', translating: 'круг людей' },
  { targetWord: 'advancement', translating: 'продвижение' },
  { targetWord: 'trend', translating: 'тенденция' },
  { targetWord: 'robotic', translating: 'роботизированный' },
  { targetWord: 'patent', translating: 'патент' },
  { targetWord: 'exhibit', translating: 'проявлять' },
  { targetWord: 'pet', translating: 'гладить' },
  { targetWord: 'reduce', translating: 'сокращать' },
  { targetWord: 'recognise', translating: 'распознавать' },
  { targetWord: 'lifelike', translating: 'как живой' },
  { targetWord: 'vulnerable', translating: 'уязвимый' },
  { targetWord: 'substitute', translating: 'замена' },
  { targetWord: 'scammer', translating: 'мошенник' },
  { targetWord: 'purchase', translating: 'приобретение' },
  { targetWord: 'purchase', translating: 'покупать' },
  { targetWord: 'low-rise', translating: 'малоэтажный' },
  { targetWord: 'kiosk', translating: 'киоск' },
  { targetWord: 'incentive', translating: 'стимул' },
  { targetWord: 'grasp', translating: 'понять' },
  { targetWord: 'patchy', translating: 'неоднородный' },
  { targetWord: 'enhance', translating: 'увеличивать' },
  { targetWord: 'enhance', translating: 'усиливать' },
  { targetWord: 'fraction', translating: 'крупица' },
  { targetWord: 'compound', translating: 'соединение' },
  { targetWord: 'subsequently', translating: 'впоследствии' },
  { targetWord: 'mimic', translating: 'имитировать' },
  { targetWord: 'turnstile', translating: 'турникет' },
  { targetWord: 'matter', translating: 'дело' },
  { targetWord: 'tackle', translating: 'решать ' },
  { targetWord: 'incidentally', translating: 'кстати' },
  { targetWord: 'trustworthy', translating: 'заслуживающий доверия' },
  { targetWord: 'shake off', translating: 'стряхивать' },
  { targetWord: 'shake off', translating: 'вытряхивать' },
  { targetWord: 'meet a deadline', translating: 'успеть в срок' },
  { targetWord: 'envision', translating: 'воображать' },
  { targetWord: 'farewell', translating: 'прощание' },
  { targetWord: 'cherish', translating: 'лелеять' },
  { targetWord: 'discharge', translating: 'выписывать' },
  { targetWord: 'devastate', translating: 'вызывать разрушения' },
  { targetWord: 'bear down on', translating: 'угрожающе надвигаться' },
  { targetWord: 'cherished', translating: 'любимый' },
  { targetWord: 'at fault', translating: 'виноватый' },
  { targetWord: 'hasten', translating: 'торопиться' },
  { targetWord: 'smash', translating: 'разбивать' },
  { targetWord: 'smash', translating: 'громить' },
  { targetWord: 'aspire', translating: 'стремиться' },
  { targetWord: 'trunk', translating: 'багажник' },
  { targetWord: 'fake', translating: 'подделывать' },
  { targetWord: 'guilty conscience', translating: 'чувство вины' },
  { targetWord: 'chipper', translating: 'бодрый' },
  { targetWord: 'fruitful', translating: 'плодотворный' },
  { targetWord: 'impose on', translating: 'навязывать' },
  { targetWord: 'loss-making', translating: 'приносящий убыток' },
  { targetWord: 'imposed', translating: 'навязанный' },
  { targetWord: 'lounge around', translating: 'бездельничать' },
  { targetWord: 'chill out', translating: 'расслабляться' },
  { targetWord: 'atelier', translating: 'ателье́' },
  { targetWord: 'repetitive', translating: 'повторяющийся' },
  { targetWord: 'idler', translating: 'бездельник' },
  { targetWord: 'turkic', translating: 'тюркская группа языков' },
  { targetWord: 'idle', translating: 'работать вхолостую' },
  { targetWord: 'boredom', translating: 'скука' },
  { targetWord: 'smuggler', translating: 'контрабандист' },
  { targetWord: 'down-to-earth', translating: 'практичный' },
  { targetWord: 'wet blanket', translating: 'зануда' },
  { targetWord: 'worrywart', translating: 'беспокойный человек' },
  { targetWord: 'narcissist', translating: 'нарцисс' },
  { targetWord: 'sanguine', translating: 'кроваво-красный цвет' },
  { targetWord: 'obstacle', translating: 'препятствие' },
  { targetWord: 'cheapskate', translating: 'скряга' },
  { targetWord: 'stray', translating: 'бродячий' },
  { targetWord: 'moonlit', translating: 'освещенный луной' },
  { targetWord: 'excessively', translating: 'чрезмерно' },
  { targetWord: 'ingenious', translating: 'находчивый' },
  { targetWord: 'suntan', translating: 'загар' },
  { targetWord: 'sick leave', translating: 'отпуск по болезни' },
  { targetWord: 'mishmash', translating: 'мешанина' },
  { targetWord: 'clay', translating: 'глина' },
  { targetWord: 'hotchpotch', translating: 'солянка' },
  { targetWord: 'confabulation', translating: 'конфабуляция' },
  { targetWord: 'permanent', translating: 'необратимый' },
  { targetWord: 'revive', translating: 'оживлять' },
  { targetWord: 'insinuate', translating: 'проникать ' },
  { targetWord: 'insinuate', translating: 'намекать' },
  { targetWord: 'lounge around', translating: 'бездельничать' },
  { targetWord: 'fraction', translating: 'крупица' },
  { targetWord: 'manipulate', translating: 'манипулировать' },
  { targetWord: 'bridge', translating: 'преодолевать' },
  { targetWord: 'chill out', translating: 'расслабляться' },
  { targetWord: 'mimic', translating: 'имитировать' },
  { targetWord: 'distort', translating: 'искажать' },
  { targetWord: 'slash', translating: 'рубить' },
  { targetWord: 'slash', translating: 'сокращать' },
  { targetWord: 'clinical trial', translating: 'клиническое исследование' },
  { targetWord: 'torment', translating: 'пытка' },
  { targetWord: 'torment', translating: 'мучение' },
  { targetWord: 'graveyard', translating: 'кладбище' },
  { targetWord: 'profound', translating: 'глубокий' },
  { targetWord: 'ominous', translating: 'зловещий' },
  { targetWord: 'unleash', translating: 'высвобождать' },
  { targetWord: 'fidget', translating: 'ёрзать' },
  { targetWord: 'contempt', translating: 'презрение' },
  { targetWord: 'arrange', translating: 'договариваться' },
  { targetWord: 'respectively', translating: 'соответственно' },
  { targetWord: 'decipher', translating: 'расшифровать' },
  { targetWord: 'deduce', translating: 'делать вывод' },
  { targetWord: 'interlocutor', translating: 'собеседник' },
  { targetWord: 'artistry', translating: 'артистичность' },
  { targetWord: 'corporative party', translating: 'корпоратив' },
  { targetWord: 'pupil', translating: 'зрачок' },
  { targetWord: 'bake', translating: 'обжигать' },
  { targetWord: 'stick around', translating: 'оставаться' },
  { targetWord: 'concussion', translating: 'сотрясение мозга' },
  { targetWord: 'stairwell', translating: 'лестничная клетка' },
  { targetWord: 'au pair', translating: 'помощник по дому; няня' },
  { targetWord: 'narrator', translating: 'рассказчик' },
  { targetWord: 'bulb', translating: 'лампочка' },
  { targetWord: 'divert', translating: 'направлять в другую сторону' },
  { targetWord: 'intercom', translating: 'домофон' },
  { targetWord: 'heir', translating: 'наследник' },
  { targetWord: 'tame', translating: 'приручать' },
  { targetWord: 'tramp', translating: 'бродяга' },
  { targetWord: 'embarrassment', translating: 'смущение' },
  { targetWord: 'destiny', translating: 'судьба' },
  { targetWord: 'tuck in', translating: 'уплетать ' },
  { targetWord: 'thoroughly', translating: 'тщательно' },
  { targetWord: 'hygiene', translating: 'гигиена' },
  { targetWord: 'brush up', translating: 'освежить в памяти' },
  { targetWord: 'slurp', translating: 'шумно прихлёбывать' },
  { targetWord: 'tribe', translating: 'племя' },
  { targetWord: 'apply', translating: 'применять' },
  { targetWord: 'put in', translating: 'уделять время' },
  { targetWord: 'enforce', translating: 'принуждать' },
  { targetWord: 'treasure', translating: 'драгоценность' },
  { targetWord: 'charm', translating: 'талисман' },
  { targetWord: 'boast', translating: 'хвастаться' },
  { targetWord: 'slump', translating: 'тяжело опускаться' },
  { targetWord: 'fatigue', translating: 'утомление' },
  { targetWord: 'inefficiently', translating: 'неэффективно' },
  { targetWord: 'binge', translating: 'объесться' },
  { targetWord: 'boundary', translating: 'граница' },
  { targetWord: 'exquisitely', translating: 'изысканно' },
  { targetWord: 'pedigree', translating: 'породистый' },
  { targetWord: 'biannual', translating: 'происходящий дважды в год' },
  { targetWord: 'waiver', translating: 'отказ от права' },
  { targetWord: 'nuts and bolts', translating: 'основная информация' },
  { targetWord: 'meter', translating: 'метр' },
  { targetWord: 'legibly', translating: 'разборчиво' },
  { targetWord: 'terminate', translating: 'завершать' },
  { targetWord: 'securely', translating: 'надёжно' },
  { targetWord: 'chairlift', translating: 'кресельный подъёмник' },
  { targetWord: 'nap', translating: 'короткий сон' },
  { targetWord: 'barren', translating: 'бесплодный' },
  { targetWord: 'barren', translating: 'неплодородный' },
  { targetWord: 'superstitious', translating: 'суеверный' },
  { targetWord: 'palm', translating: 'ладонь' },
  { targetWord: 'advisable', translating: 'целесообразный' },
  { targetWord: 'hitch', translating: 'хромать' },
  { targetWord: 'bias', translating: 'предвзятость' },
  { targetWord: 'bargain', translating: 'договариваться' },
  { targetWord: 'at stake', translating: 'на кону' },
  { targetWord: 'issue', translating: 'проблема' },
  { targetWord: 'bill of sale', translating: 'закладная' },
  { targetWord: 'merger', translating: 'слияние ' },
  { targetWord: 'average out', translating: 'усреднить' },
  { targetWord: 'outline', translating: 'обрисовывать' },
  { targetWord: 'explicitly', translating: 'явно' },
  { targetWord: 'proceed', translating: 'продолжать' },
  { targetWord: 'confidentiality', translating: 'конфиденциальность' },
  { targetWord: 'binding', translating: 'переплет' },
  { targetWord: 'fond', translating: 'любящий' },
  { targetWord: 'stir', translating: 'помешивать' },
  { targetWord: 'hail', translating: 'град' },
  { targetWord: 'shower', translating: 'лить дождем' },
  { targetWord: 'cap', translating: 'крышка' },
  { targetWord: 'drizzle', translating: 'мелкий дождь' },
  { targetWord: 'driving rain', translating: 'проливной дождь' },
  { targetWord: 'harvest', translating: 'урожай' },
  { targetWord: 'harvest', translating: 'собирать урожай' },
  { targetWord: 'wheat', translating: 'пшеница' },
  { targetWord: 'rye', translating: 'рожь' },
  { targetWord: 'cling to', translating: 'цепляться' },
  { targetWord: 'aspic', translating: 'холодец' },
  { targetWord: 'avalanche', translating: 'лавина' },
  { targetWord: 'gutter', translating: 'сточная канава' },
  { targetWord: 'intently', translating: 'внимательно' },
  { targetWord: 'harness', translating: 'ремни безопасности' },
  { targetWord: 'oversleep', translating: 'проспать' },
  { targetWord: 'quarrel with', translating: 'спорить с' },
  { targetWord: 'get sick', translating: 'заболеть' },
  { targetWord: 'miss the bus', translating: 'опоздать на автобус' },
  { targetWord: 'have a bad hair day', translating: 'день не задался' },
  { targetWord: 'quarrel', translating: 'спорить' },
  { targetWord: 'grade', translating: 'класс' },
  { targetWord: 'hectare', translating: 'гектар' },
  { targetWord: 'multistory', translating: 'многоэтажный' },
  { targetWord: 'home truth', translating: 'горькая правда' },
  { targetWord: 'home from home', translating: 'второй дом' },
  { targetWord: 'demesne', translating: 'поместье' },
  { targetWord: 'home in', translating: 'нацеливаться на' },
  { targetWord: 'take home', translating: 'зарабатывать чистыми ' },
  { targetWord: 'bring home', translating: 'довести до чьего-либо сознания' },
  { targetWord: 'be at home', translating: 'быть в своей стихии' },
  {
    targetWord: 'be home and dry',
    translating: 'быть в целости и сохранности'
  },
  {
    targetWord: 'be something to write home about',
    translating: 'есть чем похвастаться'
  },
  { targetWord: 'pile-up', translating: 'столкновение' },
  { targetWord: 'bachelor', translating: 'холостяк' },
  { targetWord: 'tug-of-war', translating: 'перетягивание каната' },
  { targetWord: 'tow truck', translating: 'эвакуатор' },
  { targetWord: 'edible', translating: 'съедобный' },
  { targetWord: 'man-of-war', translating: 'военный корабль' },
  { targetWord: 'come to terms', translating: 'примириться' },
  { targetWord: 'courtship', translating: 'ухаживание' },
  { targetWord: 'propose', translating: 'делать предложение' },
  { targetWord: 'woo', translating: 'ухаживать' },
  { targetWord: 'go steady', translating: 'иметь регулярные отношения' },
  { targetWord: 'walk down the aisle', translating: 'идти под венец' },
  { targetWord: 'aisle', translating: 'ряд ' },
  { targetWord: 'proverb', translating: 'пословица' },
  { targetWord: 'cockroach', translating: 'таракан' },
  { targetWord: 'By no means.', translating: 'Ни в коем случае.' },
  { targetWord: 'chunk', translating: 'кусок' },
  { targetWord: 'chaotic', translating: 'беспорядочный' },
  { targetWord: 'elaborate', translating: 'конкретизировать' },
  { targetWord: 'intimidate', translating: 'устрашать' },
  { targetWord: 'carry out', translating: 'выполнять' },
  { targetWord: 'expertise', translating: 'компетентность' },
  { targetWord: 'moonshine', translating: 'самогон' },
  { targetWord: 'run errands', translating: 'бегать по делам' },
  { targetWord: 'tap into something', translating: 'использовать с пользой' },
  { targetWord: 'overwhelm', translating: 'потрясать' },
  { targetWord: 'mediocre', translating: 'заурядный' },
  { targetWord: 'mediocre', translating: 'посредственный' },
  { targetWord: 'start out', translating: 'начинать' },
  { targetWord: 'accomplishment', translating: 'достижение ' },
  { targetWord: 'discouraged', translating: 'обескураженный' },
  { targetWord: 'iron out', translating: 'улаживать ' },
  { targetWord: 'breakdown', translating: 'крах' },
  { targetWord: 'scrap', translating: 'обрывок' },
  { targetWord: 'scrap', translating: 'клочок' },
  { targetWord: 'thought-provoking', translating: 'наводящий на размышления' },
  { targetWord: 'dash', translating: 'разбиваться' },
  { targetWord: 'drastically', translating: 'радикально' },
  { targetWord: 'barter', translating: 'обменивать' },
  { targetWord: 'indecent', translating: 'неподобающий' },
  { targetWord: 'keep up appearances', translating: 'соблюдать приличия' },
  { targetWord: 'boil down to', translating: 'сводиться к' },
  {
    targetWord: 'FOMO (fear of missing out)',
    translating: 'синдром упущенных возможностей'
  },
  { targetWord: 'hallucinogen', translating: 'психоделик' },
  { targetWord: 'splatter', translating: 'брызгать' },
  { targetWord: 'hothead', translating: 'сорвиголова' },
  { targetWord: 'robe', translating: 'халат' },
  { targetWord: 'fathead', translating: 'болван' },
  { targetWord: 'prohibition', translating: 'запрет' },
  { targetWord: 'anthill', translating: 'муравейник' },
  { targetWord: 'havoc', translating: 'хаос' },
  { targetWord: 'sober', translating: 'трезвый' },
  { targetWord: 'cathouse', translating: 'публичный дом' },
  { targetWord: 'pointless', translating: 'бессмысленный' },
  { targetWord: 'controversial', translating: 'спорный' },
  { targetWord: 'chapel', translating: 'часовня' },
  { targetWord: 'inappropriate', translating: 'неуместный' },
  { targetWord: 'peer', translating: 'вглядываться' },
  { targetWord: 'display', translating: 'выставлять' },
  { targetWord: 'amateur', translating: 'любитель' },
  { targetWord: 'gruesome', translating: 'ужасный' },
  { targetWord: 'pose', translating: 'излагать' },
  { targetWord: 'implication', translating: 'то, что подразумевается' },
  { targetWord: 'regardless of', translating: 'невзирая на' },
  { targetWord: 'utter', translating: 'абсолютный' },
  { targetWord: 'upbringing', translating: 'воспитание' },
  { targetWord: 'concealed', translating: 'скрытый' },
  { targetWord: 'pet peeve', translating: 'больное место' },
  { targetWord: 'tipsy', translating: 'подвыпивший' },
  { targetWord: 'brush up on', translating: 'освежить ' },
  {
    targetWord: 'brush up for a test',
    translating: 'повторять материал к тесту'
  },
  { targetWord: 'stroke', translating: 'гладить' },
  { targetWord: 'acquaintance', translating: 'знакомый' },
  { targetWord: 'blunt', translating: 'прямолинейный' },
  { targetWord: 'posture', translating: 'поза' },
  { targetWord: 'deceiver', translating: 'мошенник' },
  { targetWord: 'shallow', translating: 'неглубокий' },
  { targetWord: 'stutter', translating: 'заикаться' },
  { targetWord: 'blink', translating: 'моргать' },
  { targetWord: 'subordinate', translating: 'подчинённый' },
  { targetWord: 'cunning', translating: 'коварный' },
  { targetWord: 'beat down', translating: 'палить' },
  { targetWord: 'overcast', translating: 'затянутый облаками' },
  { targetWord: 'pause', translating: 'пауза' },
  { targetWord: 'emit', translating: 'испускать' },
  { targetWord: 'grocery', translating: 'гастроном' },
  { targetWord: 'exhaust fumes', translating: 'выхлопные газы' },
  { targetWord: 'detrimental', translating: 'вредный' },
  { targetWord: 'clog', translating: 'затруднять движение' },
  { targetWord: 'drag', translating: 'тянуть, тащить' },
  { targetWord: 'commotion', translating: 'беспорядки' },
  { targetWord: 'amongst', translating: 'среди' },
  { targetWord: 'fig', translating: 'инжир' },
  { targetWord: 'worth', translating: 'стоимость' },
  { targetWord: 'shanty', translating: 'лачуга' },
  { targetWord: 'retiree', translating: 'пенсионер' },
  { targetWord: 'upward', translating: 'направленный вверх' },
  { targetWord: 'astonish', translating: 'изумлять' },
  { targetWord: 'hobo', translating: 'бомж' },
  { targetWord: 'utility bill', translating: 'счёт за коммунальные услуги' },
  { targetWord: 'figure skating', translating: 'фигурное катание' },
  { targetWord: 'DNA', translating: 'ДНК' },
  { targetWord: 'ingenuity', translating: 'изобретательность' },
  { targetWord: 'acquisition', translating: 'приобретение' },
  { targetWord: 'utility', translating: 'полезность' },
  { targetWord: 'deprive', translating: 'лишать' },
  { targetWord: 'conspiracy', translating: 'сговор' },
  { targetWord: 'goodwill', translating: 'деловая репутация' },
  { targetWord: 'gear', translating: 'направлять' },
  { targetWord: 'demystify', translating: 'прояснять' },
  { targetWord: 'be prone to', translating: 'быть склонным ' },
  { targetWord: 'coffin', translating: 'гроб' },
  { targetWord: 'dweller', translating: 'обитатель' },
  { targetWord: 'bare', translating: 'голый' },
  { targetWord: 'strait', translating: 'тесный' },
  { targetWord: 'tenant', translating: 'арендатор' },
  { targetWord: 'bits and bobs', translating: 'всякая всячина' },
  { targetWord: 'direct', translating: 'прямолинейный' },
  { targetWord: 'host', translating: 'принимающий гостей' },
  { targetWord: 'sweaty', translating: 'потный' },
  { targetWord: 'plumbing system', translating: 'сантехника' },
  { targetWord: 'headboard', translating: 'изголовье' },
  { targetWord: 'splurge on', translating: 'серьезно потратиться' },
  { targetWord: 'wall-mounted cabinet', translating: 'шкаф навесной' },
  { targetWord: 'hay', translating: 'сено' },
  { targetWord: 'tangled', translating: 'запутанный' },
  { targetWord: 'spill', translating: 'проливать' },
  { targetWord: 'skid', translating: 'скользить' },
  { targetWord: 'plaster', translating: 'штукатурка' },
  { targetWord: 'untangle', translating: 'распутывать' },
  { targetWord: 'crayon', translating: 'цветной карандаш' },
  { targetWord: 'trouble', translating: 'неприятность, проблема' },
  { targetWord: 'plumbing system', translating: 'сантехника' },
  { targetWord: 'stain', translating: 'пятно' },
  { targetWord: 'attorney', translating: 'адвокат' },
  { targetWord: 'rewarding', translating: 'приносящий удовлетворение' },
  { targetWord: 'internship', translating: 'стажировка' },
  { targetWord: 'at once', translating: 'сразу' },
  { targetWord: 'overload', translating: 'перегрузка' },
  { targetWord: 'clutter', translating: 'беспорядок' },
  { targetWord: 'sigh', translating: 'выдох' },
  { targetWord: 'mindful', translating: 'внимательный' },
  { targetWord: 'put out', translating: 'выгонять' },
  { targetWord: 'prevent', translating: 'предотвращать' },
  { targetWord: 'relapse', translating: 'рецидив' },
  { targetWord: 'essential', translating: 'существенно важный' },
  { targetWord: 'curb', translating: 'бордюр' },
  { targetWord: 'curb', translating: 'край тротуара' },
  { targetWord: 'fluent', translating: 'свободно владеющий' },
  { targetWord: 'accustomed', translating: 'обычный' },
  { targetWord: 'relocation', translating: 'переезд' },
  { targetWord: 'dedication', translating: 'преданность' },
  { targetWord: 'relocate', translating: 'переехать' },
  { targetWord: 'die out', translating: 'вымирать' },
  { targetWord: 'maternity', translating: 'материнская забота' },
  { targetWord: 'township', translating: 'посёлок' },
  { targetWord: 'linguistic', translating: 'языковой' },
  { targetWord: 'mother tongue', translating: 'родной язык' },
  { targetWord: 'Denmark', translating: 'Дания' },
  { targetWord: 'diversity', translating: 'разнообразие' },
  { targetWord: 'endangered', translating: 'вымирающий' },
  { targetWord: 'interact', translating: 'взаимодействовать' },
  { targetWord: 'heritage', translating: 'наследие' },
  { targetWord: 'bologna', translating: 'болонская колбаса' },
  { targetWord: 'bizarre', translating: 'эксцентричный' },
  { targetWord: 'herring', translating: 'сельдь' },
  { targetWord: 'salty', translating: 'пикантный' },
  { targetWord: 'gross', translating: 'отвратительный' },
  { targetWord: 'research', translating: 'исследовать' },
  { targetWord: 'well-read', translating: 'начитанный' },
  { targetWord: 'yawn', translating: 'зевать' },
  { targetWord: 'set up', translating: 'обеспечивать' },
  { targetWord: 'result in', translating: 'приводить к' },
  { targetWord: 'take advantage of', translating: 'воспользоваться' },
  { targetWord: 'encourage', translating: 'поддерживать' },
  { targetWord: 'workforce', translating: 'рабочая сила' },
  { targetWord: 'impose', translating: 'навязывать' },
  { targetWord: 'collaborative', translating: 'совместный' },
  { targetWord: 'entrepreneur', translating: 'предприниматель' },
  { targetWord: 'job hopper', translating: 'человек, часто меняющий работу' },
  { targetWord: 'taxation', translating: 'налогообложение' },
  { targetWord: 'bargain', translating: 'сделка' },
  { targetWord: 'cosiness', translating: 'уют' },
  { targetWord: 'cut price', translating: 'снижение цен' },
  { targetWord: 'treadmill', translating: 'беговая дорожка' },
  { targetWord: 'susceptible to', translating: 'восприимчивый к' },
  { targetWord: 'fad', translating: 'последний писк моды' },
  { targetWord: 'commitment to people', translating: 'преданность людям' },
  { targetWord: 'hazel', translating: 'ореховый цвет глаз' },
  { targetWord: 'gross out', translating: 'отвращать' },
  { targetWord: 'tie', translating: 'ничья' },
  { targetWord: 'tie', translating: 'равный счет' },
  { targetWord: 'raspberry', translating: 'малина' },
  {
    targetWord: 'crush',
    translating: 'парень или девушка, в которого вы влюблены'
  },
  { targetWord: 'astrological sign', translating: 'знак зодиака' },
  { targetWord: 'addiction', translating: 'зависимость' },
  { targetWord: 'extravagant', translating: 'расточительный' },
  { targetWord: 'bling bling', translating: 'бижутерия' },
  { targetWord: 'value for money', translating: 'соотношение цены и качества' },
  {
    targetWord: 'pick up a bargain',
    translating: 'совершить выгодную покупку'
  },
  {
    targetWord: 'to shop until you drop',
    translating: 'ходить по магазинам до упаду'
  },
  { targetWord: 'discipline', translating: 'дисциплинированность' },
  { targetWord: 'loyal', translating: 'преданный' },
  { targetWord: 'butler', translating: 'дворецкий' },
  { targetWord: 'shining', translating: 'полировка' },
  { targetWord: 'paddle', translating: 'грести веслом' },
  { targetWord: 'evolve', translating: 'развиваться' },
  { targetWord: 'slippery', translating: 'скользкий' },
  { targetWord: 'anchor', translating: 'якорь' },
  { targetWord: 'intensity', translating: 'мощность' },
  { targetWord: 'exhilaration', translating: 'возбуждение' },
  { targetWord: 'novelty', translating: 'новизна' },
  { targetWord: 'brisk', translating: 'оживлённый' },
  { targetWord: 'euphoria', translating: 'эйфория' },
  { targetWord: 'surge', translating: 'всплеск' },
  { targetWord: 'literally', translating: 'без преувеличения' },
  { targetWord: 'trigger', translating: 'вызывать' },
  { targetWord: 'invigorated', translating: 'заряженный энергией' },
  { targetWord: 'oxidative', translating: 'окислительный' },
  { targetWord: 'hypothermia', translating: 'переохлаждение' },
  { targetWord: 'blood vessel', translating: 'кровеносный сосуд' },
  { targetWord: 'rehearsal', translating: 'репетиция' },
  { targetWord: 'dispel', translating: 'разгонять' },
  { targetWord: 'cable car', translating: 'вагон фуникулера' },
  { targetWord: 'cultivate', translating: 'выращивать' },
  { targetWord: 'hop', translating: 'подпрыгивать' },
  { targetWord: 'cuisine', translating: 'кухня' },
  { targetWord: 'sobering', translating: 'отрезвляющий' },
  { targetWord: 'hike up', translating: 'поднимать' },
  { targetWord: 'plateau', translating: 'плато ' },
  { targetWord: 'imprison', translating: 'заключать в тюрьму' },
  { targetWord: 'mill', translating: 'фабрика' },
  { targetWord: 'tomato plant', translating: 'томат' },
  { targetWord: 'broke', translating: 'на мели' },
  { targetWord: 'ridiculous', translating: 'нелепый' },
  { targetWord: 'chic', translating: 'шикарный' },
  { targetWord: 'gesture', translating: 'жест' },
  { targetWord: 'fancy', translating: 'причудливый' },
  { targetWord: 'unveil', translating: 'снимать покрывало' },
  { targetWord: 'tactile', translating: 'осязательный' },
  { targetWord: 'sterile', translating: 'бесплодный' },
  { targetWord: 'freak', translating: 'уродец' },
  { targetWord: 'slick', translating: 'скользкий' },
  { targetWord: 'joint', translating: 'заведение' },
  { targetWord: 'look for', translating: 'ожидать' },
  { targetWord: 'dedicated', translating: 'преданный' },
  { targetWord: 'consistently', translating: 'систематически' },
  { targetWord: 'emission', translating: 'выделение' },
  { targetWord: 'ubiquitous', translating: 'вездесущий' },
  { targetWord: 'inherently', translating: 'по своей сути' },
  { targetWord: 'mingle', translating: 'смешивать' },
  { targetWord: 'walkways', translating: 'дорожки' },
  { targetWord: 'curd', translating: 'творог' },
  { targetWord: 'luxurious', translating: 'роскошный' },
  { targetWord: 'roulade', translating: 'рулет' },
  { targetWord: 'delicious', translating: 'восхитительный' },
  { targetWord: 'scrambled', translating: 'перемешанный' },
  { targetWord: 'glob', translating: 'комок' },
  { targetWord: 'knob', translating: 'выпуклость' },
  { targetWord: 'spatula', translating: 'кухонная лопатка' },
  { targetWord: 'paddle', translating: 'весло' },
  { targetWord: 'insanity', translating: 'безумие' },
  { targetWord: 'swear off', translating: 'отказаться от' },
  { targetWord: 'bulk up', translating: 'набирать мышечную массу' },
  { targetWord: 'binge watch', translating: 'смотреть запоем' },
  { targetWord: 'stuff', translating: 'вещество' },
  { targetWord: 'diaper', translating: 'подгузник' },
  { targetWord: 'imagination', translating: 'вымысел' },
  { targetWord: 'stiff', translating: 'тип' },
  { targetWord: 'bully', translating: 'заставлять силой' },
  { targetWord: 'bend down', translating: 'Пригнись!' },
  { targetWord: 'astonished', translating: 'ошеломлённый' },
  { targetWord: 'inuit', translating: 'эскимос' },
  { targetWord: 'devastated', translating: 'опустошенный' },
  { targetWord: 'outdated', translating: 'устаревший' },
  { targetWord: 'essential', translating: 'существенный' },
  { targetWord: 'expired', translating: 'истекший' },
  { targetWord: 'bed linen', translating: 'постельное белье' },
  { targetWord: 'be aware of', translating: 'осознавать' },
  { targetWord: 'toll motorway', translating: 'платная трасса' },
  {
    targetWord: 'service station',
    translating: 'станция технического обслуживания'
  },
  { targetWord: 'exit', translating: 'выход' },
  { targetWord: 'security', translating: 'безопасность' },
  { targetWord: 'whole', translating: 'целый' },
  { targetWord: 'furious', translating: 'взбешенный' },
  { targetWord: 'Middle East', translating: 'Ближний Восток' },
  { targetWord: 'ill-treat', translating: 'плохо обращаться' },
  { targetWord: 'trivial', translating: 'незначительный' },
  { targetWord: 'ape', translating: 'человекообразная обезьяна' },
  { targetWord: 'anniversary', translating: 'годовщина' },
  { targetWord: 'social life', translating: 'социальная жизнь' },
  { targetWord: 'Tube', translating: 'метро ' },
  { targetWord: 'apply', translating: 'подавать заявление' },
  { targetWord: 'take time off', translating: 'взять перерыв' },
  { targetWord: 'guide', translating: 'экскурсовод' },
  { targetWord: 'dorm', translating: 'общежитие' },
  { targetWord: 'equally', translating: 'в равной степени' },
  { targetWord: 'give away', translating: 'отдавать' },
  { targetWord: 'greedy', translating: 'жадный' },
  { targetWord: 'wealthy', translating: 'состоятельный' },
  { targetWord: 'give away', translating: 'отдавать' },
  { targetWord: 'give up', translating: 'сдаться' },
  { targetWord: 'set up', translating: 'создавать' },
  { targetWord: 'belongings', translating: 'имущество' },
  { targetWord: 'turn up', translating: 'появляться' },
  { targetWord: 'apart from', translating: 'помимо' },
  { targetWord: 'insecure', translating: 'неуверенный в себе' },
  { targetWord: 'affectionate', translating: 'нежный' },
  { targetWord: 'sincere', translating: 'искренний' },
  { targetWord: 'keep the word', translating: 'сдержать слово' },
  { targetWord: 'take after', translating: 'быть похожим' },
  { targetWord: 'prosper', translating: 'преуспевать' },
  { targetWord: 'dynasty', translating: 'династия' },
  { targetWord: 'rare', translating: 'редкий' },
  { targetWord: 'current', translating: 'текущий' },
  { targetWord: 'current', translating: 'нынешний' },
  { targetWord: 'generation', translating: 'поколение' },
  { targetWord: 'act', translating: 'действовать' },
  { targetWord: 'ambassador', translating: 'посол' },
  { targetWord: 'fascinating', translating: 'захватывающий' },
  { targetWord: 'conscious', translating: 'сознательный' },
  { targetWord: 'take up', translating: 'начать заниматься' },
  { targetWord: 'contemporaries', translating: 'ровесники' },
  { targetWord: 'pinch', translating: 'щипать' },
  {
    targetWord: 'artificial intelligence',
    translating: 'искусственный интеллект'
  },
  {
    targetWord: 'make it up to somebody',
    translating: 'загладить вину перед кем-то'
  },
  {
    targetWord: 'when it comes to something',
    translating: 'когда дело доходит до чего-либо'
  },
  { targetWord: 'beverage', translating: 'напиток' },
  { targetWord: 'skull', translating: 'череп' },
  { targetWord: 'gather', translating: 'собирать ' },
  { targetWord: 'settle down', translating: 'осесть' },
  { targetWord: 'nail', translating: 'справиться' },
  { targetWord: 'can’t afford', translating: 'не иметь возможности позволить' },
  { targetWord: 'at some point', translating: 'в какой-то момент' },
  { targetWord: 'local cuisine', translating: 'местная кухня' },
  { targetWord: 'put (something) away', translating: 'откладывать' },
  { targetWord: 'orphanage', translating: 'детский дом' },
  { targetWord: 'sanatorium', translating: 'санаторий' },
  { targetWord: 'miracle', translating: 'чудо' },
  { targetWord: 'bum bag', translating: 'поясная сумка' },
  { targetWord: 'divided', translating: 'разделённый' },
  { targetWord: 'well-being', translating: 'благополучие' },
  { targetWord: 'tiredness', translating: 'усталость' },
  { targetWord: 'firewood', translating: 'дрова' },
  { targetWord: 'curl up', translating: 'свернуться калачиком' },
  { targetWord: 'be aware of', translating: 'быть осведомлённым о' },
  { targetWord: 'go in for', translating: 'увлекаться' },
  { targetWord: 'chore', translating: 'рутина' },
  { targetWord: 'hijacker', translating: 'угонщик' },
  { targetWord: 'faux', translating: 'искусственный' },
  { targetWord: 'harsh', translating: 'суровый' },
  { targetWord: 'jailed', translating: 'заключённый в тюрьму' },
  { targetWord: 'rummage', translating: 'обыскивать' },
  { targetWord: 'assign', translating: 'поручать' },
  { targetWord: 'municipal', translating: 'муниципальный' },
  { targetWord: 'traineeship', translating: 'стажировка' },
  { targetWord: 'wholeness', translating: 'целостность' },
  { targetWord: 'obliged', translating: 'обязанный' },
  { targetWord: 'matriarchy', translating: 'матриархат' },
  { targetWord: 'hierarchy', translating: 'иерархия' },
  { targetWord: 'starfish', translating: 'морская звезда' },
  { targetWord: 'mugger', translating: 'уличный грабитель' },
  { targetWord: 'amplifier', translating: 'усилитель' },
  { targetWord: 'facade', translating: 'фасад' },
  { targetWord: 'decor', translating: 'отделка интерьера' },
  { targetWord: 'dove', translating: 'голубь' },
  { targetWord: 'dove', translating: 'Голубь мира' },
  { targetWord: 'Caucasus Mountains', translating: 'Кавказские горы' },
  { targetWord: 'source', translating: 'источник' },
  { targetWord: 'bear cub', translating: 'медвежонок' },
  { targetWord: 'stock up', translating: 'запасаться' },
  { targetWord: 'Caucasus', translating: 'Кавказ' },
  { targetWord: 'marital status', translating: 'семейное положение' },
  { targetWord: 'bug', translating: 'надоедать' },
  { targetWord: 'staging', translating: 'постановка' },
  { targetWord: 'hypocrisy', translating: 'лицемерие' },
  { targetWord: 'disapprove', translating: 'не одобрять' },
  { targetWord: 'throughout', translating: 'всё время' },
  { targetWord: 'situate', translating: 'располагать' },
  { targetWord: 'neighbourhood', translating: 'район' },
  { targetWord: 'embankment', translating: 'набережная' },
  { targetWord: 'greet', translating: 'приветствовать' },
  { targetWord: 'grumpy', translating: 'сварливый' },
  { targetWord: 'cell', translating: 'клетка' },
  { targetWord: 'get on with', translating: 'ладить с' },
  { targetWord: 'give up', translating: 'бросить' },
  { targetWord: 'look up', translating: 'искать' },
  { targetWord: 'pick up', translating: 'поднимать' },
  { targetWord: 'turn down', translating: 'убавлять' },
  { targetWord: 'put away', translating: 'убирать' },
  { targetWord: 'find out', translating: 'узнавать' },
  { targetWord: 'throw away', translating: 'выбрасывать' },
  { targetWord: 'fill in', translating: 'заполнять' },
  { targetWord: 'stay up', translating: 'не спать' },
  { targetWord: 'steppe', translating: 'степь' },
  { targetWord: 'snail', translating: 'улитка' },
  { targetWord: 'dispossess', translating: 'лишать собственности' },
  { targetWord: 'poison', translating: 'яд' },
  { targetWord: 'vessel', translating: 'кузов' },
  { targetWord: 'monastery', translating: 'монастырь' },
  { targetWord: 'complexion', translating: 'цвет лица' },
  { targetWord: 'cure', translating: 'лечение' },
  { targetWord: 'commonly', translating: 'обычно' },
  { targetWord: 'graduation', translating: 'окончание учёбы' },
  { targetWord: 'for ages', translating: 'целую вечность' },
  { targetWord: 'Dane', translating: 'датчанин' },
  { targetWord: 'obsessive', translating: 'помешанный' },
  { targetWord: 'treat', translating: 'относиться' },
  { targetWord: 'costly', translating: 'затратный' },
  { targetWord: 'offend', translating: 'обижать' },
  { targetWord: 'decisive', translating: 'решающий' },
  { targetWord: 'hen', translating: 'курица' },
  { targetWord: 'drown', translating: 'тонуть' },
  { targetWord: 'drown', translating: 'идти ко дну' },
  { targetWord: 'traffic', translating: 'дорожное движение' },
  { targetWord: 'stressed', translating: 'напряженный' },
  { targetWord: 'previous', translating: 'предыдущий' },
  { targetWord: 'headline', translating: 'заголовок' },
  { targetWord: 'relaxed', translating: 'расслабленный' },
  { targetWord: 'speed', translating: 'скорость' },
  { targetWord: 'slow down', translating: 'замедляться' },
  { targetWord: 'stressful', translating: 'напряжённый' },
  { targetWord: 'newspaper article', translating: 'статья в газете' },
  { targetWord: 'be obsessed with', translating: 'быть одержимым чем-то' },
  { targetWord: 'newly', translating: 'недавно' },
  { targetWord: 'et cetera', translating: 'и так далее' },
  { targetWord: 'bride', translating: 'невеста' },
  { targetWord: "on one's own", translating: 'самостоятельно' },
  { targetWord: 'slicker', translating: 'плащ' },
  { targetWord: 'charge', translating: 'обвинение' },
  { targetWord: 'congestion', translating: 'затор' },
  { targetWord: 'within', translating: 'в пределах ' },
  { targetWord: 'I think so', translating: 'Думаю, что да' },
  { targetWord: 'flu', translating: 'грипп' },
  { targetWord: 'wholewheat bread', translating: 'цельнозерновой хлеб' },
  { targetWord: 'picturesque', translating: 'живописный ' },
  { targetWord: 'survive', translating: 'выживать' },
  { targetWord: 'similar', translating: 'похожий' },
  { targetWord: 'luckily', translating: 'к счастью' },
  { targetWord: 'eternal', translating: 'вечный' },
  { targetWord: 'dreamer', translating: 'мечтатель' },
  { targetWord: 'publish', translating: 'опубликовывать' },
  { targetWord: 'everywhere', translating: 'повсюду' },
  { targetWord: 'photography', translating: 'фотография' },
  { targetWord: 'each other', translating: 'друг друга' },
  { targetWord: 'luckily', translating: 'к счастью' },
  { targetWord: 'balcony', translating: 'балкон' },
  { targetWord: 'attack', translating: 'атаковать' },
  { targetWord: 'exhibition', translating: 'выставка' },
  { targetWord: 'wedding', translating: 'свадьба' },
  { targetWord: 'shout', translating: 'кричать' },
  { targetWord: 'seashore', translating: 'морское побережье' },
  { targetWord: 'immediately', translating: 'немедленно' },
  { targetWord: 'stone', translating: 'строительный камень' },
  { targetWord: 'suddenly', translating: 'вдруг ' },
  { targetWord: 'lovely', translating: 'прекрасный' },
  { targetWord: 'furious', translating: 'яростный' },
  { targetWord: 'rain', translating: 'дождь' },
  { targetWord: 'cold', translating: 'холодный' },
  { targetWord: 'adore', translating: 'обожать' },
  { targetWord: 'have a good time', translating: 'хорошо проводить время' },
  { targetWord: 'awful', translating: 'ужасный' },
  { targetWord: 'feed', translating: 'кормить' },
  { targetWord: 'great', translating: 'огромный' },
  { targetWord: 'terrible', translating: 'ужасный' },
  { targetWord: 'see off', translating: 'провожать' },
  { targetWord: 'cigarette butt', translating: 'окурок' },
  { targetWord: 'cobbled street', translating: 'мощёная улица' },
  { targetWord: 'knee', translating: 'колено' },
  { targetWord: 'deal with', translating: 'решать' },
  { targetWord: 'pine', translating: 'сосна' },
  { targetWord: 'suffer', translating: 'страдать ' },
  { targetWord: 'embarrass', translating: 'смущать' },
  { targetWord: 'tent', translating: 'палатка' },
  { targetWord: 'medicine', translating: 'лекарство' },
  { targetWord: 'accomplish', translating: 'выполнять' },
  { targetWord: 'overcome', translating: 'преодолевать' },
  { targetWord: 'pregnant', translating: 'беременная' },
  { targetWord: 'jealous', translating: 'ревнивый' },
  { targetWord: 'appearance', translating: 'внешний вид' },
  { targetWord: 'exciting', translating: 'захватывающий' },
  { targetWord: 'distract', translating: 'отвлекать' },
  { targetWord: 'interrupt', translating: 'прерывать' },
  { targetWord: 'litre', translating: 'литр' },
  { targetWord: 'box', translating: 'коробка' },
  { targetWord: 'agree', translating: 'соглашаться' },
  { targetWord: 'sweat', translating: 'пот' },
  { targetWord: 'can', translating: 'алюминиевая банка' },
  { targetWord: 'for example', translating: 'например' },
  { targetWord: 'at least', translating: 'по меньшей мере' },
  { targetWord: 'contain', translating: 'содержать' },
  { targetWord: 'bottle', translating: 'бутылка' },
  { targetWord: 'tin', translating: 'жестяная банка' },
  { targetWord: 'onion', translating: 'луковица' },
  { targetWord: 'greasy', translating: 'жирный' },
  { targetWord: 'missing', translating: 'недостающий' },
  { targetWord: 'staple', translating: 'товар первой необходимости' },
  { targetWord: 'boil', translating: 'температура кипения' },
  { targetWord: 'boil', translating: 'варить' },
  { targetWord: 'enormous', translating: 'огромный' },
  { targetWord: 'town hall', translating: 'городская ратуша' },
  { targetWord: 'available', translating: 'доступный' },
  { targetWord: 'in advance', translating: 'заранее' },
  { targetWord: 'violin', translating: 'скрипка' },
  { targetWord: 'move', translating: 'двигаться; передвигать' },
  { targetWord: 'neighbour', translating: 'сосед' },
  { targetWord: 'noisy', translating: 'шумный' },
  { targetWord: 'bark', translating: 'лаять' },
  { targetWord: 'choose', translating: 'выбирать' },
  { targetWord: 'baby', translating: 'младенец' },
  { targetWord: 'friendly', translating: 'дружелюбный' },
  { targetWord: 'argue', translating: 'обсуждать' },
  { targetWord: 'cry', translating: 'плакать' },
  { targetWord: 'century', translating: 'век' },
  { targetWord: 'frightened', translating: 'испуганный' },
  { targetWord: 'nervous', translating: 'взволнованный' },
  { targetWord: 'priest', translating: 'священник' },
  { targetWord: 'strange', translating: 'странный' },
  { targetWord: 'guest', translating: 'гость ' },
  { targetWord: 'go back', translating: 'брать начало' },
  { targetWord: 'spend', translating: 'проводить' },
  { targetWord: 'ghost', translating: 'привидение' },
  { targetWord: 'believe', translating: 'верить' },
  { targetWord: 'cooker', translating: 'плита' },
  { targetWord: 'cupboard', translating: 'шкафчик' },
  { targetWord: 'chest of drawers', translating: 'комод' },
  { targetWord: 'coffee table', translating: 'журнальный столик' },
  { targetWord: 'tin', translating: 'олово' },
  { targetWord: 'millionaire', translating: 'миллионер' },
  { targetWord: 'dead', translating: 'мёртвый' },
  { targetWord: 'murder', translating: 'убийство' },
  { targetWord: 'somebody', translating: 'кто-то' },
  { targetWord: 'juridical', translating: 'юридический' },
  { targetWord: 'garden', translating: 'сад' },
  { targetWord: 'country house', translating: 'загородный дом' },
  { targetWord: 'happen', translating: 'происходить' },
  { targetWord: 'arrive', translating: 'прибывать' },
  { targetWord: 'midnight', translating: 'полночь' },
  { targetWord: 'kangaroo', translating: 'кенгуру' },
  { targetWord: 'hat', translating: 'шляпа' },
  { targetWord: 'sweater', translating: 'свитер' },
  { targetWord: 'shirt', translating: 'рубашка' },
  { targetWord: 'T-shirt', translating: 'футболка' },
  { targetWord: 'skirt', translating: 'юбка' },
  { targetWord: 'jacket', translating: 'пиджак' },
  { targetWord: 'shoes', translating: 'обувь' },
  { targetWord: 'dress', translating: 'платье' },
  { targetWord: 'be born', translating: 'рождаться' },
  { targetWord: 'jeans', translating: 'джинсы' },
  { targetWord: 'tonight', translating: 'сегодняшний вечер ' },
  { targetWord: 'still', translating: 'всё ещё' },
  { targetWord: 'similar', translating: 'похожий' },
  { targetWord: 'download', translating: 'скачивать' },
  { targetWord: 'prejudice', translating: 'предубеждение' },
  { targetWord: 'head', translating: 'голова' },
  { targetWord: 'record', translating: 'грампластинка' },
  { targetWord: 'discoverer', translating: 'первооткрыватель' },
  { targetWord: 'concert', translating: 'концерт' },
  { targetWord: 'orchestra', translating: 'оркестр' },
  { targetWord: 'hire', translating: 'нанимать' },
  { targetWord: 'happening', translating: 'событие' },
  { targetWord: 'suspect', translating: 'подозревать' },
  { targetWord: 'story', translating: 'рассказ' },
  { targetWord: 'life', translating: 'жизнь' },
  { targetWord: 'impossible', translating: 'невероятный' },
  { targetWord: 'obsession', translating: 'одержимость' },
  { targetWord: 'pick up', translating: 'подобрать' },
  { targetWord: 'smile', translating: 'улыбка' },
  { targetWord: 'replica', translating: 'точная копия' },
  { targetWord: 'decide', translating: 'принимать решение' },
  { targetWord: 'sauna', translating: 'сауна' },
  { targetWord: 'today', translating: 'сегодня' },
  { targetWord: 'adventure', translating: 'приключение' },
  { targetWord: 'hobby', translating: 'хобби' },
  { targetWord: 'adult', translating: 'взрослый' },
  { targetWord: 'shop', translating: 'магазин' },
  { targetWord: 'survey', translating: 'обследование' },
  { targetWord: 'perfect', translating: 'идеальный' },
  { targetWord: 'possibly', translating: 'может быть' },
  { targetWord: 'practical', translating: 'практический' },
  { targetWord: 'noise', translating: 'шум' },
  { targetWord: 'buy', translating: 'покупать' },
  { targetWord: 'call⁄phone a taxi', translating: 'вызывать такси' },
  { targetWord: 'come', translating: 'приходить' },
  { targetWord: 'dance the tango', translating: 'танцевать танго' },
  { targetWord: 'draw', translating: 'рисовать' },
  { targetWord: 'draw', translating: 'чертить' },
  { targetWord: 'find', translating: 'обнаруживать' },
  { targetWord: 'give', translating: 'дарить' },
  { targetWord: 'hear', translating: 'слышать' },
  { targetWord: 'thanks', translating: 'благодарность' },
  { targetWord: 'but', translating: 'только' },
  { targetWord: 'after', translating: 'после' },
  { targetWord: 'before', translating: 'прежде' },
  { targetWord: 'then', translating: 'затем' },
  { targetWord: 'and', translating: 'и' },
  { targetWord: 'because', translating: 'потому что' },
  { targetWord: 'or', translating: 'или' },
  { targetWord: 'I’m really sorry.', translating: 'Мне действительно жаль.' },
  {
    targetWord: 'There’s a free table over there.',
    translating: 'Там есть свободный столик.'
  },
  { targetWord: 'continue', translating: 'продолжать' },
  { targetWord: 'fascinating', translating: 'захватывающий' },
  { targetWord: 'take place', translating: 'проходить' },
  { targetWord: 'comfortable', translating: 'удобный' },
  { targetWord: 'holiday', translating: 'отпуск' },
  { targetWord: 'enjoy', translating: 'получать удовольствие' },
  { targetWord: 'temperature', translating: 'температура' },
  { targetWord: 'celebrate', translating: 'праздновать' },
  { targetWord: 'especially', translating: 'особенно' },
  { targetWord: 'favourite', translating: 'любимый' },
  { targetWord: 'similar', translating: 'похожий' },
  { targetWord: "take one's time", translating: 'не торопиться' },
  { targetWord: 'hardly ever', translating: 'почти никогда' },
  { targetWord: 'invite', translating: 'призывать' },
  { targetWord: 'canteen', translating: 'фляга' },
  { targetWord: 'cycle', translating: 'ездить на велосипеде' },
  { targetWord: 'canteen', translating: 'буфет ' },
  { targetWord: 'pretty', translating: 'симпатичный' },
  { targetWord: 'eye', translating: 'глаз' },
  { targetWord: 'adopted', translating: 'приёмный' },
  { targetWord: 'famous', translating: 'знаменитый' },
  { targetWord: 'good-looking', translating: 'привлекательный' },
  { targetWord: 'airline', translating: 'авиакомпания' },
  { targetWord: 'the moon', translating: 'луна' },
  { targetWord: 'What colour is it?', translating: 'Какого цвета?' },
  { targetWord: 'hat', translating: 'шляпа' },
  { targetWord: 'first', translating: 'сначала' },
  { targetWord: 'lift', translating: 'лифт' },
  { targetWord: 'darling', translating: 'дорогой' },
  { targetWord: 'imagine', translating: 'представлять' },
  { targetWord: 'imagine', translating: 'воображать' },
  { targetWord: 'kiss', translating: 'целовать' },
  { targetWord: 'lorry', translating: 'фура' },
  { targetWord: 'lorry', translating: 'грузовик' },
  { targetWord: 'suitcase', translating: 'чемодан' },
  { targetWord: 'elevator', translating: 'лифт' },
  { targetWord: 'divorced', translating: 'разведенный' },
  { targetWord: 'hat', translating: 'шляпа' },
  { targetWord: 'aunt', translating: 'тётя' },
  { targetWord: 'father', translating: 'отец' },
  { targetWord: 'niece', translating: 'племянница' },
  { targetWord: 'girlfriend', translating: 'подруга' },
  { targetWord: 'divorced', translating: 'разведенный' },
  { targetWord: 'grandfather', translating: 'дедушка' },
  { targetWord: 'son', translating: 'сын' },
  { targetWord: 'cap', translating: 'кепка' },
  { targetWord: 'boyfriend', translating: 'парень' },
  { targetWord: 'behave', translating: 'вести себя' },
  { targetWord: 'sacred', translating: 'священный' },
  { targetWord: 'junk', translating: 'обломки' },
  { targetWord: 'collect', translating: 'собирать' },
  { targetWord: 'slave', translating: 'раб' },
  { targetWord: 'cornet', translating: 'корнет' },
  { targetWord: 'waiter', translating: 'официант' },
  { targetWord: 'politician', translating: 'политик' },
  { targetWord: 'lonely', translating: 'одинокий' },
  { targetWord: 'together', translating: 'вместе' },
  { targetWord: 'housewife', translating: 'домохозяйка' },
  { targetWord: 'footballer', translating: 'футболист' },
  { targetWord: 'lawyer', translating: 'юрист' },
  { targetWord: 'outside', translating: 'внешний' },
  { targetWord: 'inside', translating: 'внутренность' },
  { targetWord: 'normally', translating: 'обычно' },
  { targetWord: 'similar', translating: 'похожий' },
  { targetWord: 'success', translating: 'успех' },
  { targetWord: 'married', translating: 'женатый' },
  { targetWord: 'same', translating: 'одинаковый' },
  { targetWord: 'both', translating: 'оба' },
  { targetWord: 'scrambled eggs', translating: 'омлет' },
  { targetWord: 'different', translating: 'разный' },
  { targetWord: 'disaster', translating: 'бедствие' },
  { targetWord: 'single', translating: 'единственный' },
  { targetWord: 'literature', translating: 'литература' },
  { targetWord: 'article', translating: 'статья' },
  { targetWord: 'auxiliary', translating: 'запасной' },
  { targetWord: 'wine', translating: 'вино' },
  { targetWord: 'supermarket', translating: 'супермаркет' },
  { targetWord: 'heading', translating: 'заголовок' },
  { targetWord: 'idea', translating: 'мысль' },
  { targetWord: 'boring', translating: 'скучный' },
  { targetWord: 'glass', translating: 'стакан' },
  { targetWord: 'zebra crossing', translating: 'пешеходный переход' },
  { targetWord: 'cook', translating: 'повар' },
  { targetWord: 'too', translating: 'тоже' },
  { targetWord: 'fantastic', translating: 'великолепный' },
  { targetWord: 'incredible', translating: 'невероятный' },
  { targetWord: 'Britain', translating: 'Британия' },
  { targetWord: 'a lot of', translating: 'много' },
  { targetWord: 'just', translating: 'совсем недавно' },
  { targetWord: 'first', translating: 'первый' },
  { targetWord: 'for example', translating: 'например' },
  { targetWord: 'finally', translating: 'в конце концов' },
  { targetWord: 'next', translating: 'следующий' },
  { targetWord: 'then', translating: 'затем' },
  { targetWord: 'so', translating: 'поэтому' },
  { targetWord: 'How far is it?', translating: 'Насколько это далеко?' },
  { targetWord: 'because of', translating: 'из-за' },
  { targetWord: 'in my opinion', translating: 'по моему мнению' },
  { targetWord: 'that is why', translating: 'вот почему' },
  { targetWord: 'point', translating: 'указывать' },
  { targetWord: 'watch', translating: 'наручные часы' },
  { targetWord: 'identity card', translating: 'удостоверение личности' },
  { targetWord: 'guess', translating: 'догадаться' },
  { targetWord: 'please', translating: 'доставлять удовольствие' },
  { targetWord: 'glasses', translating: 'очки' },
  { targetWord: 'magazine', translating: 'журнал' },
  { targetWord: 'purse', translating: 'дамская сумочка' },
  { targetWord: 'number', translating: 'количество' },
  { targetWord: 'wallet', translating: 'бумажник' },
  { targetWord: 'underscore', translating: 'подчёркивать' },
  { targetWord: 'call', translating: 'называть' },
  { targetWord: 'excuse', translating: 'оправдывать' },
  { targetWord: 'dot', translating: 'точка' },
  { targetWord: 'dash', translating: 'тире' },
  { targetWord: 'centre', translating: 'центр' },
  { targetWord: 'hyphen', translating: 'дефис' },
  { targetWord: 'What’s your surname?', translating: 'Как ваша фамилия?' },
  { targetWord: 'How do you spell it?', translating: 'Как это по буквам?' },
  {
    targetWord: "What's your phone number?",
    translating: 'Какой у Вас номер телефона?'
  },
  { targetWord: 'eighty', translating: 'восемьдесят' },
  { targetWord: 'sixty', translating: 'шестьдесят' },
  { targetWord: 'business', translating: 'профессия, занятие' },
  { targetWord: 'Madrid', translating: 'Мадрид' },
  { targetWord: 'again', translating: 'снова' },
  { targetWord: 'Edinburgh', translating: 'Эдинбург' },
  { targetWord: 'delicious', translating: 'вкусный' },
  { targetWord: 'fifty', translating: 'пятьдесят' },
  { targetWord: 'quiz', translating: 'короткий тест' },
  { targetWord: 'ninety', translating: 'девяносто' },
  { targetWord: 'complete', translating: 'заканчивать' },
  { targetWord: 'complete', translating: 'дополнять ' },
  { targetWord: 'complete', translating: 'заполнять ' },
  { targetWord: 'organizer', translating: 'органайзер' },
  { targetWord: 'sentence', translating: 'предложение ' },
  { targetWord: 'have a nice day', translating: 'Хорошего дня' },
  { targetWord: 'they', translating: 'он или она' },
  { targetWord: 'exercise', translating: 'упражнение' },
  { targetWord: 'language', translating: 'язык' },
  { targetWord: 'gap', translating: 'различие' },
  { targetWord: 'conversation', translating: 'беседа' },
  { targetWord: 'question', translating: 'вопрос' },
  { targetWord: 'write', translating: 'писать' },
  { targetWord: 'answer', translating: 'ответ' },
  { targetWord: 'know', translating: 'знать' },
  { targetWord: 'page', translating: 'страница' },
  { targetWord: 'practise', translating: 'практиковаться' },
  { targetWord: 'sorry', translating: 'сожалеющий' },
  { targetWord: 'picture', translating: 'фотография' },
  { targetWord: 'email', translating: 'электронная почта' },
  { targetWord: 'remember', translating: 'помнить' },
  { targetWord: 'read', translating: 'читать' },
  { targetWord: 'photo', translating: 'фото' },
  { targetWord: 'pardon', translating: 'извинение' },
  { targetWord: 'say', translating: 'сказать' },
  { targetWord: 'complete', translating: 'заполнять ' },
  { targetWord: '' },
  { targetWord: 'filling', translating: 'наполнитель' },
  { targetWord: 'integer', translating: 'целое число' },
  { targetWord: 'suppose', translating: 'предполагать' },
  { targetWord: 'squad', translating: 'бригада' },
  { targetWord: 'flimsy', translating: 'неосновательный' },
  { targetWord: 'thorough', translating: 'подробный' },
  { targetWord: 'flawed', translating: 'некорректный' },
  { targetWord: 'boldly', translating: 'дерзко' },
  { targetWord: 'shorthand', translating: 'условное обозначение' },
  { targetWord: 'missile', translating: 'реактивный снаряд' },
  { targetWord: 'missile', translating: 'ракета' },
  { targetWord: 'angular', translating: 'угловатый' },
  { targetWord: 'assertion', translating: 'утверждение' },
  { targetWord: 'oath', translating: 'клятва' },
  { targetWord: 'devoted', translating: 'преданный' },
  { targetWord: 'resilient', translating: 'устойчивый' },
  { targetWord: 'cohesion', translating: 'сплоченность' },
  { targetWord: 'repercussion', translating: 'последствие' },
  { targetWord: 'renowned', translating: 'знаменитый' },
  { targetWord: 'credible', translating: 'заслуживающий доверия' },
  { targetWord: 'intrinsically', translating: 'в действительности' },
  { targetWord: 'cohesive', translating: 'сплоченный' },
  { targetWord: 'indigenous', translating: 'коренной' },
  { targetWord: 'devastatingly', translating: 'разрушительно' },
  { targetWord: 'lance', translating: 'стремительно двигаться' },
  { targetWord: 'intrusive', translating: 'навязчивый' },
  { targetWord: 'indigenous', translating: 'коренной' },
  { targetWord: 'devastatingly', translating: 'разрушительно' },
  { targetWord: 'intrusive.', translating: 'навязчивый' },
  { targetWord: 'wonder', translating: 'чудо' },
  { targetWord: 'persecution', translating: 'гонение' },
  { targetWord: 'hatred', translating: 'ненависть' },
  { targetWord: 'extinction', translating: 'вымирание' },
  {
    targetWord: 'extinction',
    translating: 'вымирание'
  },
  {
    targetWord: 'extinction',
    translating: 'исчезновение'
  },
  { targetWord: 'hatred', translating: 'чувство ненависти' },
  { targetWord: 'persecution', translating: 'преследование' },
  { targetWord: 'persecution.', translating: 'преследование' },
  { targetWord: 'persecution.', translating: 'гонение' },
  { targetWord: 'vicious', translating: 'злой' },
  { targetWord: 'malicious', translating: 'злонамеренный' },
  { targetWord: 'resemblance', translating: 'сходство' },
  { targetWord: 'resemblance', translating: 'подобие' },
  { targetWord: 'growling', translating: 'рычать' },
  { targetWord: 'wreak', translating: 'наносить' },
  { targetWord: 'wreak', translating: 'обрушить' },
  { targetWord: 'merit', translating: 'заслуга' },
  { targetWord: 'merit', translating: 'достоинство' },
  { targetWord: 'ounce', translating: 'унция ' },
  { targetWord: 'electric outlet', translating: 'розетка' },
  { targetWord: 'shared', translating: 'совместный' },
  { targetWord: 'void', translating: 'пустота' },
  { targetWord: 'gipsy', translating: 'бродяга' },
  { targetWord: 'Gipsy', translating: 'цыган' },
  { targetWord: 'yarn', translating: 'рассказ' },
  { targetWord: 'yarn', translating: 'пряжа' },
  { targetWord: 'suspense', translating: 'неизвестность' },
  { targetWord: 'political entity', translating: 'политическая организация' },
  { targetWord: 'likelihood', translating: 'вероятностный' },
  { targetWord: 'relic', translating: 'пережиток' },
  { targetWord: 'depreciate', translating: 'умалять' },
  { targetWord: 'pending', translating: 'в ожидании' },
  { targetWord: 'invoked', translating: 'вызванный' },
  { targetWord: 'trial and error', translating: 'метод проб и ошибок' },
  { targetWord: 'by the way', translating: 'кстати' },
  { targetWord: 'strenuous', translating: 'требующий усилий' },
  { targetWord: 'strenuous', translating: 'напряженный' },
  { targetWord: 'or so', translating: 'приблизительно' },
  { targetWord: 'trail', translating: 'тропа' },
  { targetWord: 'go through', translating: 'проходить через' },
  { targetWord: 'go through', translating: 'просматривать' },
  { targetWord: 'mess up', translating: 'сделать ошибку' },
  { targetWord: 'leisurely', translating: 'неторопливый' },
  { targetWord: 'irrespective', translating: 'независимо' },
  { targetWord: 'leverage', translating: 'использовать' },
  { targetWord: 'and', translating: 'и' },
  { targetWord: 'all-important', translating: 'крайне важный' },
  { targetWord: 'flaw', translating: 'недостаток' },
  { targetWord: 'trial and error', translating: 'метод проб и ошибок' },
  { targetWord: 'by the way', translating: 'кстати' },
  { targetWord: 'strenuous', translating: 'требующий усилий' },
  { targetWord: 'strenuous', translating: 'напряженный' },
  { targetWord: 'or so', translating: 'приблизительно' },
  { targetWord: 'trail', translating: 'тропа' },
  { targetWord: 'go through', translating: 'проходить через' },
  { targetWord: 'go through', translating: 'просматривать' },
  { targetWord: 'mess up', translating: 'сделать ошибку' },
  { targetWord: 'leisurely', translating: 'неторопливый' },
  { targetWord: 'thoughtful', translating: 'содержательный' },
  { targetWord: 'fulfilling', translating: 'удовлетворяющий' },
  { targetWord: 'demise', translating: 'кончина' },
  { targetWord: 'warfare', translating: 'война' },
  { targetWord: 'coup', translating: 'государственный переворот' },
  { targetWord: 'intelligence', translating: 'разведка' },
  { targetWord: 'overt', translating: 'очевидный' },
  { targetWord: 'assassination', translating: 'убийство ' },
  { targetWord: 'mercenary', translating: 'наемный солдат' },
  { targetWord: 'overthink', translating: 'зацикливаться' },
  { targetWord: 'embark', translating: 'приступать' },
  { targetWord: 'decimal', translating: 'десятичная дробь' },
  { targetWord: 'decimal', translating: 'десятичный' },
  { targetWord: 'accessibility', translating: 'доступность' },
  { targetWord: 'accessibility', translating: 'доступность' },
  { targetWord: 'override', translating: 'аннулирование' },
  { targetWord: 'override', translating: 'перевешивать' },
  { targetWord: 'embed', translating: 'вставлять' },
  { targetWord: 'embed', translating: 'присоединять' },
  { targetWord: 'defendant', translating: 'ответчик' },
  { targetWord: 'legacy', translating: 'наследство' },
  { targetWord: 'legacy', translating: 'наследие' },
  { targetWord: 'slant', translating: 'уклон' },
  { targetWord: 'slant', translating: 'иметь наклонное положение' },
  { targetWord: 'agile', translating: 'проворный' },
  { targetWord: 'agile', translating: 'подвижный' },
  { targetWord: 'Scrum', translating: 'драка' },
  { targetWord: 'pop', translating: 'хлопок' },
  { targetWord: 'clamp', translating: 'зажим' },
  { targetWord: 'clamp', translating: 'сжимать' },
  { targetWord: 'clamp', translating: 'скоба' },
  { targetWord: 'stub', translating: 'окурок' },
  { targetWord: 'nest', translating: 'гнездо' },
  { targetWord: 'property', translating: 'собственность' },
  { targetWord: 'property', translating: 'отличительная черта' },
  { targetWord: 'property', translating: 'недвижимость' },
  { targetWord: 'property', translating: 'имущество' },
  { targetWord: 'path', translating: 'контур' },
  { targetWord: 'delimiter', translating: 'разделитель данных' },
  { targetWord: 'representation', translating: 'представительство' },
  { targetWord: 'Subtly', translating: 'исподволь' },
  { targetWord: 'harsh', translating: 'суровый' },
  { targetWord: 'harsh', translating: 'грубый' },
  { targetWord: 'shape-shifter', translating: 'оборотень' },
  { targetWord: 'superiority', translating: 'превосходство' },
  { targetWord: 'lateral thinking', translating: 'нестандартное мышление' },
  { targetWord: 'inclined', translating: 'склонный' },
  { targetWord: 'simplistic', translating: 'упрощенный' },
  { targetWord: 'at will', translating: 'по желанию' },
  {
    targetWord: 'smoke and mirrors',
    translating: 'пыль в глаза; обман и дымовая завеса'
  },
  { targetWord: 'vibrant', translating: 'энергичный' },
  { targetWord: 'edge', translating: 'преимущество' },
  { targetWord: 'simplified', translating: 'упрощенный' },
  {
    targetWord: 'specified',
    translating: 'заданный'
  },
  {
    targetWord: 'specified',
    translating: 'определенный'
  },
  { targetWord: 'computed', translating: 'вычисленный' },
  { targetWord: 'look into', translating: 'изучать' },
  { targetWord: 'catch up', translating: 'догонять' },
  { targetWord: 'ripped', translating: 'порванный' },
  { targetWord: 'fad', translating: 'последний писк моды' },
  {
    targetWord: 'trials and tribulations',
    translating: 'испытания и невзгоды'
  },
  { targetWord: 'prompt', translating: 'командная строка' },
  { targetWord: 'command prompt', translating: 'интерфейс командной строки' },
  { targetWord: 'put in', translating: 'класть' },
  { targetWord: 'impoverished', translating: 'нуждающийся' },
  { targetWord: 'put in', translating: 'вкладывать' },
  { targetWord: 'embed', translating: 'вставлять' },
  { targetWord: 'asset', translating: 'полезное качество' },
  { targetWord: 'asset', translating: 'актив' },
  { targetWord: 'cater', translating: 'обслуживать' },
  { targetWord: 'simultaneous', translating: 'одновременный' },
  { targetWord: 'unlike', translating: 'в отличие от' },
  { targetWord: 'burst', translating: 'лопаться' },
  {
    targetWord: 'obsolete',
    translating: 'устаревший'
  },
  {
    targetWord: 'obsolete',
    translating: 'вышедший из употребления'
  },
  { targetWord: 'thrill', translating: 'дрожать' },
  { targetWord: 'endurance', translating: 'выносливость' },
  { targetWord: 'unaware', translating: 'не знающий' },
  { targetWord: 'bravery', translating: 'храбрость' },
  { targetWord: 'asylum', translating: 'убежище' },
  { targetWord: 'asylum', translating: 'психиатрическая больница' },
  { targetWord: 'debunk', translating: 'разоблачать' },
  { targetWord: 'vice versa', translating: 'наоборот' },
  { targetWord: 'pluck', translating: 'выдёргивать' },
  { targetWord: 'aid', translating: 'помощь' },
  { targetWord: 'amateur', translating: 'любительский' },
  { targetWord: 'disguise', translating: 'притворство' },
  { targetWord: 'disguise', translating: 'маскировка' },
  { targetWord: 'disguise', translating: 'маскировать' },
  { targetWord: 'blessing in disguise', translating: 'нет худа без добра' },
  { targetWord: 'maroon', translating: 'бордовый цвет' },
  { targetWord: 'maroon', translating: 'сигнальный фейерверк' },
  { targetWord: 'maroon', translating: 'красно-коричневый' },
  { targetWord: 'anchor', translating: 'якорь' },
  { targetWord: 'anchor', translating: 'главная опора' },
  { targetWord: 'markup', translating: 'разметка' },
  { targetWord: 'markup', translating: 'разметка' },
  { targetWord: 'with flying colours', translating: 'блестяще' },
  { targetWord: 'squid', translating: 'кальмар' },
  { targetWord: 'indigestion', translating: 'несварение' },
  { targetWord: 'torture', translating: 'пытка' },
  { targetWord: 'hectic', translating: 'суматошный; лихорадочный' },
  { targetWord: 'savour', translating: 'насладиться' },
  { targetWord: 'rhyme', translating: 'рифма' },
  { targetWord: 'rhyme', translating: 'стихотворение' },
  { targetWord: 'preconceived', translating: 'предвзятый' },
  { targetWord: 'hustle and bustle', translating: 'шум и суета' },
  { targetWord: 'enthused', translating: 'полный энтузиазма' },
  { targetWord: 'crack of dawn', translating: 'рассвет' },
  { targetWord: 'scared stiff', translating: 'до смерти напуганный' },
  { targetWord: 'careful', translating: 'тщательный' },
  { targetWord: 'count on', translating: 'рассчитывать на' },
  { targetWord: 'toggle', translating: 'переключатель' },
  { targetWord: 'trapped', translating: 'загнанный в угол' },
  { targetWord: 'assurance', translating: 'уверенность' },
  { targetWord: 'current', translating: 'течение' },
  { targetWord: 'backlash', translating: 'отрицательная реакция' },
  { targetWord: 'torrent', translating: 'ливень' },
  { targetWord: 'duration', translating: 'длительность' },
  { targetWord: 'pug', translating: 'мопс' },
  { targetWord: 'evenly', translating: 'равномерно' },
  { targetWord: 'represent', translating: 'олицетворять' },
  { targetWord: 'give in', translating: 'сдаваться' },
  { targetWord: 'give in', translating: 'поддаваться' },
  { targetWord: 'opacity', translating: 'полупрозрачность' },
  { targetWord: 'justify', translating: 'выравнивать текст' },
  { targetWord: 'align', translating: 'выравнивать' },
  { targetWord: 'uppercase', translating: 'прописная буква' },
  { targetWord: 'uppercase', translating: 'верхний регистр' }
];
